default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>


development:
  <<: *default
  database: rails_wallet_development

test:
  <<: *default
  database: rails_wallet_test

production:
  primary: &primary_production
    <<: *default
    database: rails_wallet_production
  cache:
    <<: *primary_production
    database: rails_wallet_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_wallet_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_wallet_production_cable
    migrations_paths: db/cable_migrate
